// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_GSxRk78Byh1N_FvxtqkBcoMYj-YrYc0',
    appId: '1:355006325980:web:98cfac585b25d27cf24019',
    messagingSenderId: '355006325980',
    projectId: 'basics-6f7a8',
    authDomain: 'basics-6f7a8.firebaseapp.com',
    storageBucket: 'basics-6f7a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu4JDrLqHDx8P_DRmK3ocOSQRtvpQhkW4',
    appId: '1:355006325980:android:5d10080410c227e4f24019',
    messagingSenderId: '355006325980',
    projectId: 'basics-6f7a8',
    storageBucket: 'basics-6f7a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj5SHyLSLOzE7p4ntYk8KGjD0lYX0QuPw',
    appId: '1:355006325980:ios:52904725dcb6457cf24019',
    messagingSenderId: '355006325980',
    projectId: 'basics-6f7a8',
    storageBucket: 'basics-6f7a8.appspot.com',
    iosBundleId: 'com.example.fireBasics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj5SHyLSLOzE7p4ntYk8KGjD0lYX0QuPw',
    appId: '1:355006325980:ios:52904725dcb6457cf24019',
    messagingSenderId: '355006325980',
    projectId: 'basics-6f7a8',
    storageBucket: 'basics-6f7a8.appspot.com',
    iosBundleId: 'com.example.fireBasics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_GSxRk78Byh1N_FvxtqkBcoMYj-YrYc0',
    appId: '1:355006325980:web:6735bf8373d6ada7f24019',
    messagingSenderId: '355006325980',
    projectId: 'basics-6f7a8',
    authDomain: 'basics-6f7a8.firebaseapp.com',
    storageBucket: 'basics-6f7a8.appspot.com',
  );
}
